### ISSUE TITLE
[CON] - Docs Layout Refactor 

### ISSUE THREAD

**Issue by priyashpatil** [continuedev/continue#1887]
As per the discussion with the team the following is the summary for new docs structure:

The docs will be organized into top-level sections by navbar links, defined like [here](https://github.com/continuedev/continue/blob/nate/esm/docs/docusaurus.config.js#L79-L85), or in their documentation [here](https://docusaurus.io/docs/api/themes/configuration#navbar-items). Each of these navbar headers will link to a separate “sidebar”.

Under each sidebar, I’m denoting each [page](https://github.com/continuedev/continue/blob/nate/esm/docs/sidebars.js#L19-L20) by a bullet point, and nested bullet points indicate a collapsible category like [here.](https://github.com/continuedev/continue/blob/nate/esm/docs/sidebars.js#L32-L43)

**“Docs” Sidebar**

- [x] Install #2007 
  - [x] Introduction #2007 
  - [x] VS Code #2007 
  - [x] JetBrains #2007 
  - [x] How to use Continue #2007 
  - [x] Troubleshooting #2007 
- [ ] Tutorials
  - [ ]  Fundamentals #2035
  - [ ] Example configuration files #2035
  - [ ] How to select an LLM (this would be a combination of [Select Providers](https://docs.continue.dev/setup/select-provider) and [Select Models](https://docs.continue.dev/setup/select-model)) #2035
  - [x] [Authentication](https://docs.continue.dev/setup/configuration#authentication) #2035
  - [x] How to setup Codestral #2035
  - [x] Using Llama 3.1 with Continue #2035
  - [ ] How to use config.json (a page to describe the basics of config.json: short list of features, where it is stored, how to edit it, how it is reloaded automatically, [etc.](https://docs.continue.dev/customization/overview)) #2035
- [ ] Features
  - [ ] Chat Sidebar
  - [ ] Codebase retrieval - #1995
  - [ ] Tab autocomplete - #1995
  - [ ] Inline edits
  - [ ] Context Providers - #1995
  - [ ] Slash Commands - #1995
  - [ ] Prompt files - #1995
  - [ ] Quick actions - #1995
  - [ ] [we will probably add more later]
- [x] Privacy - #1910
  - [x] Development Data - #1910
  - [x] Telemetry - #1910
  - [x] Privacy Policy - #1910
- [ ] Advanced
  - [ ] Customizing prompts (this page should explain that Continue automatically detects prompts from the model name, but if you need to customize: Continue uses Handlebars syntax to define prompt formats, and you can customize 1. Chat template, 2. /edit template, and 3. Autocomplete template) (then there are sections for “Customizing the chat template”, “Customizing the /edit prompt”, and “Customizing the autocomplete prompt”) 
  - [ ] [Defining a Custom LLM Provider](https://docs.continue.dev/setup/configuration#defining-a-custom-llm-provider) #2035
  - [ ] [Building a custom context provider](https://docs.continue.dev/customization/context-providers#building-your-own-context-provider) #2035
  - [ ] [Building a custom slash command](https://docs.continue.dev/customization/slash-commands#custom-slash-commands) #2035

**“Reference” Sidebar**
- [x] Config.json reference #2007  #2035
- [x] LLM providers #2007  #2035
- [x] [Embeddings providers](https://docs.continue.dev/features/codebase-embeddings#embeddings-providers) #2035
  - [x] Transformers.js #2035
  - [x] Ollama #2035
  - [x] etc… #2035
- [x] [Reranking providers](https://docs.continue.dev/features/codebase-embeddings#reranking-providers) #2035
  - [x] Voyage #2035
  - [x] Cohere #2035
  - [x] etc… #2035
- [ ] [Context providers](https://docs.continue.dev/customization/context-providers#built-in-context-providers) (single page)
- [ ] [Slash commands](https://docs.continue.dev/customization/slash-commands#built-in-slash-commands) (single page)

**“Community” Sidebar**
- [x] Code of Conduct #2035
- [ ] Roadmap #2035
- [ ] FAQ 
- [ ] Contributing #2035
- [x] Changelog
  - [x] VS Code #2035
  - [x] JetBrains #2035
- [x] Support #2035
---
Related Issues: #1741 #1745 #1803 #1707 #1344

**Comment by Patrick-Erichsen** [comment]
This all looks great to me 👍

**Comment by priyashpatil** [comment]
@Patrick-Erichsen are we keeping this on?

**Comment by Patrick-Erichsen** [comment]
@priyashpatil I think we can close out 👍
