### ISSUE TITLE
[CON-285] Meta Issue for Autocomplete Improvements

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#2615]
This issue encompasses issues with the quality of output and DX for Tab Autocomplete
- [ ] https://github.com/continuedev/continue/issues/2748
- [x] https://github.com/continuedev/continue/issues/2712
- [ ] https://github.com/continuedev/continue/issues/3425 (JetBrains)

Other thoughts:
- Better logging
- Bug where completion not shown when right before a parenthesis
- Stop at \n\n if overrunning bracket or reverse indentation
- Ellipsis/signatures only when Root Path Context is too large (see `indexing/chunk/code.ts`)
- Explore git
- Copy buffer (decay rank based on when it was copied, filter PII)
- Test that we are reusing requests correctly (this is `CompletionStreamer.ts`)
- Make sure that we are cancelling requests

<sub>[CON-285](https://linear.app/continue/issue/CON-285/meta-issue-for-autocomplete-improvements)</sub>

**Comment by tomasz-stefaniak** [comment]
Another thing to solve: when getting a definition in Python, it only grabs the firs line with the name of the class, ignores class contents:

<img width="1459" alt="image" src="https://github.com/user-attachments/assets/c0d99477-a197-409b-bb09-1c5786bbb985">

**Comment by Capsar** [comment]
What settings for autocompletion are there possible in the `config.json`?

Ideas:
- How to use the template specifically for the model that is used.
- Include context providers in the template to be included in the prompt: For example: {{repo-map}} in the template.

I found this, where it states the default is to include other files, but none are shown in the output logs of Continue.dev:
https://github.com/continuedev/continue/blob/fbeb2e4fe15d4b434a30a136f74b672485c852d9/core/util/parameters.ts

Futhermore, I found a relevant issue:
#3506
